### PR TITLE
debian_codename set to ansible_distribution_release. Customizable rep…

### PR DESCRIPTION
**Pull request by damko**
…o URL

### CODE REVIEW

**Comment by ramondelafuente** [comment]
This is a BC break (of sorts) because the repo defaults to `us` while it was hardcoded to `nl` before :-)
Not a big problem, but maybe add a note in the readme on that?

Also, a rebase is needed..

**Comment by ramondelafuente** [comment]
I merged a rebased version of this. Thanks!

**Comment by damko** [comment]
you are welcome! thank you for your neat job!

**Comment by damko** [comment]
I just read the previous comment. I don't see why it's a BC break. Even if it defaults to US (which I believe to be the right choice) instead of NL it will still work. By updating the ansible book the user can set the wanted repo URL, right?

**Comment by ramondelafuente** [comment]
It still works, but now retrieves files from a source much farther away (in our case), which suddenly _might_ have unexpected results without us changing the playbook.

But yeah, "bc-break" might be a stretch. I implied as much by saying "of sorts", plus I merged it so... :-)

**Pull request closed without merging**
