### PR TITLE
maybe this would help some users

### PR DESCRIPTION
**Pull request by damko**

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Good call.. I wanted to make the version explicit but I did not want to break backward compatibility (and this role was releases for Wheezy first).

`{{ ansible_distribution_release }}` is actually nicer as a default since that would still be BC, and also make the parameter optional.

**Comment by ramondelafuente** [comment]
Could you update the PR to make the default value `{{ ansible_distribution_release }}`?

**Comment by damko** [comment]
sure. Working on this

**Comment by damko** [comment]
I will just do this:

debian_codename: '{{ ansible_distribution_release }}'

So that it can be overwritten. I don't think it's gonna be necessary to anybody but we hate hard-coded, right?

**Comment by damko** [comment]
done. Pls check PR

**Pull request merged**
